### ISSUE TITLE
sql文件是空的，没有数据，帮忙传一份

### ISSUE THREAD

**Issue by shangdiuser** [hzq-up/dragonshopping#2]
sql文件是空的，没有数据，帮忙传一份

**Comment by hzq-up** [comment]
已经push了数据库文件，求个赞！！！！

**Comment by hzq-up** [comment]
已经push到项目里了，求赞！！！

在 2019-12-02 21:59:42，"ipk003" <notifications@github.com> 写道：


sql文件是空的，没有数据，帮忙传一份
